//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranOntology.Models.QuranEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuranDBEntities : DbContext
    {
        public QuranDBEntities()
            : base("name=QuranDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ontology> Ontologies { get; set; }
        public virtual DbSet<Refrence> Refrences { get; set; }
        public virtual DbSet<Quran> Qurans { get; set; }
        public virtual DbSet<QuranTranslationByAhmedAli> QuranTranslationByAhmedAlis { get; set; }
        public virtual DbSet<QuranUrduByJalandhri> QuranUrduByJalandhris { get; set; }
        public virtual DbSet<NounVerb> NounVerbs { get; set; }
        public virtual DbSet<WordRefrence> WordRefrences { get; set; }
    }
}
