//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranOntology.Models.QuranEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quran
    {
        public Quran()
        {
            this.Ontologies = new HashSet<Ontology>();
            this.Refrences = new HashSet<Refrence>();
            this.QuranTranslationByAhmedAlis = new HashSet<QuranTranslationByAhmedAli>();
            this.QuranUrduByJalandhris = new HashSet<QuranUrduByJalandhri>();
            this.WordRefrences = new HashSet<WordRefrence>();
        }
    
        public int ID { get; set; }
        public byte DatabaseID { get; set; }
        public byte SuraID { get; set; }
        public short VerseID { get; set; }
        public string AyahText { get; set; }
    
        public virtual ICollection<Ontology> Ontologies { get; set; }
        public virtual ICollection<Refrence> Refrences { get; set; }
        public virtual ICollection<QuranTranslationByAhmedAli> QuranTranslationByAhmedAlis { get; set; }
        public virtual ICollection<QuranUrduByJalandhri> QuranUrduByJalandhris { get; set; }
        public virtual ICollection<WordRefrence> WordRefrences { get; set; }
    }
}
