//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranOntology.Models.QuranEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refrence
    {
        public int ID { get; set; }
        public byte SuraID { get; set; }
        public short VerseID { get; set; }
        public int OntologiesID { get; set; }
    
        public virtual Ontology Ontology { get; set; }
        public virtual Quran Quran { get; set; }
    }
}
