//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranOntology.Models.QuranEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordRefrence
    {
        public long ID { get; set; }
        public Nullable<long> NounVerbID { get; set; }
        public Nullable<long> NounVerbRefrenceID { get; set; }
        public Nullable<byte> RefrenceSuraID { get; set; }
        public Nullable<short> RefrenceVerseID { get; set; }
    
        public virtual NounVerb NounVerb { get; set; }
        public virtual NounVerb NounVerb1 { get; set; }
        public virtual Quran Quran { get; set; }
    }
}
